Repository Cambridge-ICCS/FTorch, pull requests merged in 2023-11, with the labels that each got.

#66 Python QC workflow
  .github/workflows/python_qc.yaml
  examples/1_SimpleNet/simplenet.py
  examples/1_SimpleNet/simplenet_infer_fortran
  examples/1_SimpleNet/simplenet_infer_python.py
  examples/2_ResNet18/resnet18.py
  examples/n_c_and_cpp/resnet18.py
  examples/n_c_and_cpp/resnet_infer_python.py
Labels: documentation, enhancement

#67 CMake fix
  README.md
  examples/1_SimpleNet/README.md
  examples/2_ResNet18/Makefile
  examples/2_ResNet18/README.md
  src/CMakeLists.txt
Labels: bug, enhancement

#60 add mwe for fypp preprocessor
  .githooks/pre-commit
  .github/workflows/fypp.yml
  README.md
  examples/1_SimpleNet/simplenet_infer_fortran.f90
  examples/2_ResNet18/resnet_infer_fortran.f90
  examples/tensor_tests/CMakeLists.txt
  examples/tensor_tests/test_tensor.f90
  src/ftorch.f90
  src/ftorch.fypp
Labels: enhancement

#69 Patch on example utils files.
  examples/1_SimpleNet/pt2ts.py
  examples/2_ResNet18/pt2ts.py
Labels: bug
