Repository Cambridge-ICCS/FTorch, pull requests merged in 2023-10, with the labels that each got.

#41 First pass rebranding to FTorch in main readme.
  README.md
  examples/1_SimpleNet/README.md
  examples/2_ResNet18/README.md
  examples/README.md
  examples/n_c_and_cpp/README.md
  src/CMakeLists.txt
  src/README.md
  src/ctorch.cpp
  src/ctorch.h
  src/ftorch.f90
  utils/README.md
Labels: documentation

#44 Tidy example Fortran code
  examples/2_ResNet18/resnet_infer_fortran.f90
Labels: enhancement

#33 Update Documentation following TF-lib documentation
  README.md
Labels: documentation

#47 Fix incorrect variable name
  examples/2_ResNet18/resnet_infer_fortran.f90
Labels: bug

#46 Ensure strings end with c_null_char
  README.md
  examples/1_SimpleNet/simplenet_infer_fortran.f90
  examples/2_ResNet18/resnet_infer_fortran.f90
  examples/tensor_tests/test_tensor.f90
  src/ftorch.f90
Labels: enhancement
