Repository Cambridge-ICCS/FTorch, pull requests merged in 2024-07, with the labels that each got.

#123 Update Windows help
  pages/troubleshooting.md
Labels: documentation

#148 Fix LaTeX Markdown in example 4
  examples/4_MultiIO/README.md
Labels: documentation

#150 Fix `requires_grad` optional argument
  examples/2_ResNet18/resnet_infer_fortran.f90
  src/ftorch.f90
  src/ftorch.fypp
Labels: bug

#156 add interface to delete all torch objects
  examples/1_SimpleNet/simplenet_infer_fortran.f90
  examples/2_ResNet18/resnet_infer_fortran.f90
  examples/3_MultiGPU/simplenet_infer_fortran.f90
  examples/4_MultiIO/multiionet_infer_fortran.f90
  pages/examples.md
  src/ftorch.f90
  src/ftorch.fypp
Labels: documentation, enhancement

#155 add subroutine to delete arrays of tensors
  examples/1_SimpleNet/simplenet_infer_fortran.f90
  examples/2_ResNet18/resnet_infer_fortran.f90
  examples/3_MultiGPU/simplenet_infer_fortran.f90
  examples/4_MultiIO/multiionet_infer_fortran.f90
  pages/examples.md
  src/ftorch.f90
  src/ftorch.fypp
Labels: enhancement

#159 Update README.md with citations
  README.md
Labels: documentation

#145 Add tests for different Fortran standards
  .github/workflows/test_suite.yml
  README.md
  pages/cmake.md
  src/CMakeLists.txt
Labels: enhancement, hackathon
