Repository Cambridge-ICCS/FTorch, pull requests merged in 2024-12, with the labels that each got.

#204 Apply CMake formatting
  .github/workflows/static_analysis.yml
  examples/1_SimpleNet/CMakeLists.txt
  examples/2_ResNet18/CMakeLists.txt
  examples/3_MultiGPU/CMakeLists.txt
  examples/4_MultiIO/CMakeLists.txt
  examples/5_Looping/CMakeLists.txt
  examples/6_Autograd/CMakeLists.txt
  examples/n_c_and_cpp/CMakeLists.txt
  pages/developer.md
  requirements.txt
  src/CMakeLists.txt
Labels: enhancement

#207 wip: debugging windows CI
  .github/workflows/test_suite_windows.yml
Labels: bug

#206 Linting for shell and GitHub Actions
  .github/workflows/build_docs.yml
  .github/workflows/fypp_checks.yml
  .github/workflows/static_analysis.yml
  .github/workflows/test_suite_ubuntu.yml
  .github/workflows/test_suite_windows.yml
  pages/developer.md
  requirements.txt
  run_integration_tests.sh
Labels: testing

#139 Overload elementary operations
  examples/6_Autograd/autograd.f90
  examples/6_Autograd/autograd.py
  pages/autograd.md
  pages/developer.md
  pages/examples.md
  run_integration_tests.sh
  src/CMakeLists.txt
  src/ctorch.cpp
  src/ctorch.h
  src/ftorch.F90
  src/ftorch.fypp
Labels: enhancement
