Repository Cambridge-ICCS/FTorch, pull requests merged in 2024-10, with the labels that each got.

#182 Bump the minimum required CMake in all CMakeLists to 3.5
  examples/1_SimpleNet/CMakeLists.txt
  examples/2_ResNet18/CMakeLists.txt
  examples/3_MultiGPU/CMakeLists.txt
  examples/4_MultiIO/CMakeLists.txt
  examples/5_Looping/CMakeLists.txt
  examples/6_Autograd/CMakeLists.txt
  examples/n_c_and_cpp/CMakeLists.txt
  src/CMakeLists.txt
Labels: documentation

#181 feat: use get_shape in to_array subroutines
  src/ftorch.f90
  src/ftorch.fypp
Labels: enhancement

#166 Use assertions rather than print statements in tests
  .github/workflows/fypp.yml
  .github/workflows/test_suite.yml
  examples/1_SimpleNet/CMakeLists.txt
  examples/1_SimpleNet/simplenet.py
  examples/1_SimpleNet/simplenet_infer_fortran.f90
  examples/1_SimpleNet/simplenet_infer_python.py
  examples/2_ResNet18/CMakeLists.txt
  examples/2_ResNet18/resnet18.py
  examples/2_ResNet18/resnet_infer_fortran.f90
  examples/3_MultiGPU/simplenet_infer_fortran.f90
  examples/4_MultiIO/CMakeLists.txt
  examples/4_MultiIO/multiionet.py
  examples/4_MultiIO/multiionet_infer_fortran.f90
  examples/4_MultiIO/multiionet_infer_python.py
  examples/6_Autograd/CMakeLists.txt
  examples/6_Autograd/autograd.f90
  examples/6_Autograd/autograd.py
  pages/examples.md
  run_integration_tests.sh
  src/CMakeLists.txt
  src/ftorch_test_utils.f90
  src/ftorch_test_utils.fypp
Labels: testing

#173 Extend FTorch to cover 5-dimensional tensors.
  src/ftorch.f90
  src/ftorch.fypp
Labels: enhancement
