Repository Cambridge-ICCS/FTorch, pull requests merged in 2025-01, with the labels that each got.

#215 Lean on compiler
  examples/2_ResNet18/resnet_infer_fortran.f90
  examples/6_Autograd/autograd.f90
  src/ftorch.F90
  src/ftorch.fypp
  src/ftorch_test_utils.f90
  src/ftorch_test_utils.fypp
Labels: bug

#216 Call from_blob inside from_array
  src/ftorch.F90
  src/ftorch.fypp
  src/test/unit/test_constructors.pf
Labels: bug, autograd

#76 Unit tests (using pFunit)
  .github/workflows/test_suite_ubuntu.yml
  .github/workflows/test_suite_windows.yml
  pages/testing.md
  run_integration_tests.sh
  run_test_suite.bat
  run_test_suite.sh
  src/CMakeLists.txt
  src/ftorch.F90
  src/ftorch.fypp
  src/ftorch_test_utils.f90
  src/ftorch_test_utils.fypp
  src/test/README.md
  src/test/unit/CMakeLists.txt
  src/test/unit/README.md
  src/test/unit/test_constructors.pf
Labels: enhancement, autograd, testing

#225 Unit tests for operator overloading; fix scalar bug
  src/ctorch.cpp
  src/ctorch.h
  src/ftorch.F90
  src/ftorch.fypp
  src/test/unit/CMakeLists.txt
  src/test/unit/test_tensor_operator_overloads.pf
Labels: bug, autograd

#233 Minor build tweaks
  README.md
  examples/1_SimpleNet/CMakeLists.txt
  examples/2_ResNet18/CMakeLists.txt
  examples/3_MultiGPU/CMakeLists.txt
  examples/4_MultiIO/CMakeLists.txt
  examples/5_Looping/CMakeLists.txt
  examples/6_Autograd/CMakeLists.txt
  src/CMakeLists.txt
  src/test/unit/CMakeLists.txt
Labels: documentation

#237 Ensure strides array initialised to zero
  src/ftorch.F90
  src/ftorch.fypp
Labels: bug

#231 Move input array checks out of autograd example
  examples/6_Autograd/autograd.f90
  examples/README.md
  src/test/unit/test_constructors.pf
  src/test/unit/test_tensor_operator_overloads.pf
Labels: autograd, testing

#247 Implement `torch_tensor_minus` for taking negative of a tensor
  src/ctorch.cpp
  src/ctorch.h
  src/ftorch.F90
  src/ftorch.fypp
  src/test/unit/test_tensor_operator_overloads.pf
Labels: enhancement, autograd

#238 Make use of pFUnit test fixtures
  src/test/unit/CMakeLists.txt
  src/test/unit/test_constructors.pf
  src/test/unit/test_tensor_constructors.pf
  src/test/unit/test_tensor_operator_overloads.pf
Labels: autograd, testing

#239 Add unit tests for tensor interrogation
  .github/workflows/test_suite_ubuntu.yml
  examples/6_Autograd/autograd.f90
  pages/testing.md
  run_test_suite.sh
  src/test/unit/CMakeLists.txt
  src/test/unit/test_tensor_interrogation.pf
  src/test/unit/test_tensor_interrogation_cuda.pf
Labels: autograd, testing

#254 Require `device_type` argument for `torch_model_load`
  README.md
  examples/1_SimpleNet/simplenet_infer_fortran.f90
  examples/2_ResNet18/resnet_infer_fortran.f90
  examples/3_MultiGPU/simplenet_infer_fortran.f90
  examples/4_MultiIO/multiionet_infer_fortran.f90
  examples/5_Looping/bad/fortran_ml_mod.f90
  examples/5_Looping/good/fortran_ml_mod.f90
  examples/6_Autograd/README.md
  examples/CMakeLists.txt
  pages/examples.md
  pages/testing.md
  pages/updates.md
  src/CMakeLists.txt
  src/ftorch.F90
  src/ftorch.fypp
Labels: bug, gpu

#267 Use `get_device_index` method in test
  src/test/unit/test_tensor_interrogation_cuda.pf
Labels: bug

#251 Add `get_dtype` and `get_device_type` methods for `torch_tensor`
  src/ctorch.cpp
  src/ctorch.h
  src/ftorch.F90
  src/ftorch.fypp
  src/test/unit/test_tensor_interrogation.pf
  src/test/unit/test_tensor_interrogation_cuda.pf
Labels: enhancement, testing
