Repository Cambridge-ICCS/FTorch, pull requests merged in 2025-05, with the labels that each got.

#373 `requires_grad` *should* be carried through expressions
  src/ctorch.cpp
  src/ftorch.F90
  src/ftorch.fypp
  test/unit/test_tensor_autograd.pf
  test/unit/test_tensor_constructors_destructors.pf
  test/unit/test_tensor_interrogation.pf
  test/unit/test_tensor_operator_overloads.pf
  test/unit/test_tensor_operator_overloads_autograd.pf
Labels: bug, autograd

#374 Docs on overloaded assignment operator
  pages/tensor.md
  pages/troubleshooting.md
Labels: documentation, autograd

#376 Convert Reading seminars to presentation
  FTorch.md
  pages/presentations.md
Labels: documentation

#377 Fix bug in implementation of wrapper function `torch_from_blob` (#365)
  src/ctorch.cpp
Labels: bug
