Repository Cambridge-ICCS/FTorch, pull requests merged in 2025-03, with the labels that each got.

#303 Drop `torch_tensor_to_array`
  examples/6_Autograd/autograd.f90
  pages/examples.md
  pages/updates.md
  src/ctorch.cpp
  src/ctorch.h
  src/ftorch.F90
  src/ftorch.fypp
  test/unit/test_tensor_constructors_destructors.pf
  test/unit/test_tensor_operator_overloads.pf
Labels: bug, autograd

#272 Checks for inconsistent device types
  examples/6_Autograd/autograd.f90
  pages/examples.md
  pages/updates.md
  src/ctorch.cpp
  src/ctorch.h
  src/ftorch.F90
  src/ftorch.fypp
  test/unit/test_tensor_constructors_destructors.pf
  test/unit/test_tensor_operator_overloads.pf
Labels: bug, autograd, testing, gpu

#200 JOSS paper submission
  .github/workflows/JOSS_paper_pdf.yml
  paper/paper.bib
  paper/paper.md
Labels: documentation

#288 Hook up `requires_grad`
  examples/6_Autograd/autograd.f90
  pages/autograd.md
  src/ctorch.cpp
  src/ctorch.h
  src/ftorch.F90
  src/ftorch.fypp
  test/unit/test_tensor_constructors_destructors.pf
  test/unit/test_tensor_interrogation.pf
Labels: enhancement, autograd

#270 MPI example
  .github/workflows/test_suite_ubuntu.yml
  examples/3_MultiGPU/multigpu_infer_fortran.f90
  examples/7_MPI/CMakeLists.txt
  examples/7_MPI/README.md
  examples/7_MPI/mpi_infer_fortran.f90
  examples/7_MPI/mpi_infer_python.py
  examples/7_MPI/pt2ts.py
  examples/7_MPI/requirements.txt
  examples/7_MPI/simplenet.py
  examples/CMakeLists.txt
  examples/README.md
  pages/examples.md
  pages/hpc.md
  run_test_suite.sh
Labels: documentation, testing

#289 Rework scalar multiplication and division
  examples/7_Autograd/autograd.f90
  pages/autograd.md
  src/ftorch.F90
  src/ftorch.fypp
  test/unit/test_tensor_operator_overloads.pf
Labels: enhancement, autograd

#322 Fix some broken links in the docs
  pages/cmake.md
  pages/updates.md
Labels: documentation

#324 Typo correction of is_training variable description in the ftorch API.
  src/ftorch.F90
  src/ftorch.fypp
Labels: documentation

#319 Add tests for constructing after destructing
  test/unit/test_tensor_constructors_destructors.pf
Labels: testing

#326 Mention test changes in changelog
  CHANGELOG.md
Labels: documentation

#331 Add `fypp` to requirements
  pages/developer.md
  requirements-dev.txt
Labels: documentation

#333 Add news section to website
  FTorch.md
Labels: documentation

#286 Implement `torch_tensor_backward`
  CHANGELOG.md
  examples/8_Autograd/autograd.f90
  pages/autograd.md
  src/ctorch.cpp
  src/ctorch.h
  src/ftorch.F90
  src/ftorch.fypp
  test/unit/CMakeLists.txt
  test/unit/test_tensor_operator_overloads.pf
  test/unit/test_tensor_operator_overloads_autograd.pf
Labels: enhancement, autograd

#339 Spring cleaning
  pages/autograd.md
  test/unit/test_tensor_constructors_destructors.pf
  test/unit/test_tensor_interrogation.pf
  test/unit/test_tensor_interrogation_cuda.pf
  test/unit/test_tensor_operator_overloads.pf
  test/unit/test_tensor_operator_overloads_autograd.pf
Labels: testing

#342 Expose `retain_graph` argument for `backward`
  CHANGELOG.md
  pages/autograd.md
  src/ctorch.cpp
  src/ctorch.h
  src/ftorch.F90
  src/ftorch.fypp
  test/unit/test_tensor_autograd.pf
Labels: enhancement, autograd

#341 Implement zeroing of gradients
  CHANGELOG.md
  pages/autograd.md
  src/ctorch.cpp
  src/ctorch.h
  src/ftorch.F90
  src/ftorch.fypp
  test/unit/CMakeLists.txt
  test/unit/test_tensor_autograd.pf
Labels: enhancement, autograd

#338 Implement `torch_tensor_zero`
  CHANGELOG.md
  pages/tensor.md
  src/ctorch.cpp
  src/ctorch.h
  src/ftorch.F90
  src/ftorch.fypp
  test/unit/CMakeLists.txt
  test/unit/test_tensor_manipulation.pf
Labels: enhancement
